"""initfd

Revision ID: 9b6efacc31e1
Revises: 595bcbdec3ca
Create Date: 2024-09-23 23:19:34.574279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b6efacc31e1'
down_revision: Union[str, None] = '595bcbdec3ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admins', ['id'])
    op.add_column('feedbacks', sa.Column('phone', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'feedbacks', ['id'])
    op.create_unique_constraint(None, 'orders', ['id'])
    op.create_unique_constraint(None, 'products', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_constraint(None, 'feedbacks', type_='unique')
    op.drop_column('feedbacks', 'phone')
    op.drop_constraint(None, 'admins', type_='unique')
    # ### end Alembic commands ###
